### PR TITLE
libplatsupport/imx6: add missing field

### PR DESCRIPTION
**Pull request by axel-h**
fixes https://github.com/seL4/util_libs/issues/58

### CODE REVIEW

**Comment by xurtis** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Review by xurtis — APPROVED** [review]

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by xurtis** [comment]
This has been merged and changes should be pushed out to github soon.

**Comment by axel-h** [comment]
Thanks!

**Pull request merged**
