### PR TITLE
fix ZYNQ UART issues

### PR DESCRIPTION
**Pull request by axel-h**

### CODE REVIEW

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 8a15bd509424079aa2ee484797f9394ad5de2320

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - util_libs - EXT-axel-h-axel-patch-1-43 | SUCCESSFUL |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-1-43 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-1-43 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    28-Sep-2020 11:17:25	Build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-1-43 - style #3 (CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR-3) started building on agent A local agent 1
    28-Sep-2020 11:17:25	I run on the Bamboo server!
    28-Sep-2020 11:17:25	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR
    28-Sep-2020 11:17:25	Executing build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-1-43 - style #3 (CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR-3)
    28-Sep-2020 11:17:25	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR/. (location: .)
    28-Sep-2020 11:17:25	Artifact 'code' prepared in 40.69 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR/./code.tar.gz
    28-Sep-2020 11:17:25	Running pre-build action: VCS Version Collector
    28-Sep-2020 11:17:25	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    28-Sep-2020 11:17:25	+ tar xf code.tar.gz --recursive-unlink
    28-Sep-2020 11:17:25	Finished task 'Untar code' with result: Success
    28-Sep-2020 11:17:25	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    28-Sep-2020 11:17:25	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR
    28-Sep-2020 11:17:25	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    28-Sep-2020 11:17:25	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    28-Sep-2020 11:17:25	+ cd util_libs
    28-Sep-2020 11:17:25	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR/seL4_tools/misc/style.sh
    28-Sep-2020 11:17:25	++ git merge-base 8a15bd509424079aa2ee484797f9394ad5de2320 0a642200152e84327e6921b390a0aa0a421673ef
    28-Sep-2020 11:17:25	+ git diff --name-only 8a15bd509424079aa2ee484797f9394ad5de2320 0a642200152e84327e6921b390a0aa0a421673ef
    28-Sep-2020 11:17:25	Formatted  libplatsupport/src/chardev.h
    28-Sep-2020 11:17:25	Unchanged  libplatsupport/src/mach/zynq/serial.c
    28-Sep-2020 11:17:25	+ git diff --exit-code
    28-Sep-2020 11:17:25	diff --git a/libplatsupport/src/chardev.h b/libplatsupport/src/chardev.h
    28-Sep-2020 11:17:25	index c6787e3..d4652eb 100644
    28-Sep-2020 11:17:25	--- a/libplatsupport/src/chardev.h
    28-Sep-2020 11:17:25	+++ b/libplatsupport/src/chardev.h
    28-Sep-2020 11:17:25	@@ -19,7 +19,7 @@ struct dev_defn {
    28-Sep-2020 11:17:25	     enum chardev_id id;
    28-Sep-2020 11:17:25	     uintptr_t paddr;
    28-Sep-2020 11:17:25	     int   size;
    28-Sep-2020 11:17:25	-    const int* irqs;
    28-Sep-2020 11:17:25	+    const int *irqs;
    28-Sep-2020 11:17:25	     int (*init_fn)(const struct dev_defn *defn,
    28-Sep-2020 11:17:25	                    const ps_io_ops_t *ops,
    28-Sep-2020 11:17:25	                    struct ps_chardevice *dev);
    28-Sep-2020 11:17:25	@@ -30,11 +30,11 @@ static inline void *chardev_map(
    28-Sep-2020 11:17:25	     const ps_io_ops_t *ops)
    28-Sep-2020 11:17:25	 {
    28-Sep-2020 11:17:25	     return ps_io_map(
    28-Sep-2020 11:17:25	-            (ps_io_mapper_t*)&ops->io_mapper, // cast removes "const" qualifier
    28-Sep-2020 11:17:25	-            (uintptr_t)dev->paddr,
    28-Sep-2020 11:17:25	-            dev->size,
    28-Sep-2020 11:17:25	-            0, // map uncached
    28-Sep-2020 11:17:25	-            PS_MEM_NORMAL);
    28-Sep-2020 11:17:25	+               (ps_io_mapper_t *)&ops->io_mapper, // cast removes "const" qualifier
    28-Sep-2020 11:17:25	+               (uintptr_t)dev->paddr,
    28-Sep-2020 11:17:25	+               dev->size,
    28-Sep-2020 11:17:25	+               0, // map uncached
    28-Sep-2020 11:17:25	+               PS_MEM_NORMAL);
    28-Sep-2020 11:17:25	 }
    28-Sep-2020 11:17:25	 
    28-Sep-2020 11:17:25	 int uart_init(
    28-Sep-2020 11:17:25	@@ -56,7 +56,7 @@ ssize_t uart_write(
    28-Sep-2020 11:17:25	 
    28-Sep-2020 11:17:25	 ssize_t uart_read(
    28-Sep-2020 11:17:25	     ps_chardevice_t *dev,
    28-Sep-2020 11:17:25	-    void* vdata,
    28-Sep-2020 11:17:25	+    void *vdata,
    28-Sep-2020 11:17:25	     size_t count,
    28-Sep-2020 11:17:25	     chardev_callback_t rcb UNUSED,
    28-Sep-2020 11:17:25	     void *token UNUSED);
    28-Sep-2020 11:17:25	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR-3-ScriptBuildTask-3540339945608917614.sh] was 1 while expected 0
    28-Sep-2020 11:17:25	Finished task 'Check style of changed files' with result: Failed
    28-Sep-2020 11:17:25	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    28-Sep-2020 11:17:25	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR
    28-Sep-2020 11:17:25	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    28-Sep-2020 11:17:25	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    28-Sep-2020 11:17:25	+ cd util_libs
    28-Sep-2020 11:17:25	++ echo ssh://git@bitbucket.ts.data61.csiro.au:7999/sel4/util_libs.git
    28-Sep-2020 11:17:25	++ cut -d/ -f4
    28-Sep-2020 11:17:25	+ bb_proj=sel4
    28-Sep-2020 11:17:25	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4 util_libs
    28-Sep-2020 11:17:25	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    28-Sep-2020 11:17:25	+ SCRIPT_DIR=/scripts/bb_code_insights
    28-Sep-2020 11:17:25	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    28-Sep-2020 11:17:25	+ BBS_PROJECT=sel4
    28-Sep-2020 11:17:25	+ BBS_REPO=util_libs
    28-Sep-2020 11:17:25	+ REPORT_TO_RUN=astyle
    28-Sep-2020 11:17:25	++ git rev-parse HEAD
    28-Sep-2020 11:17:25	+ COMMIT_ID=8a15bd509424079aa2ee484797f9394ad5de2320
    28-Sep-2020 11:17:25	+ REPORT_KEY=astyle.report
    28-Sep-2020 11:17:25	+ set +x
    28-Sep-2020 11:17:25	+ report_file=astyle_report.json
    28-Sep-2020 11:17:25	+ annotations_file=astyle_annotations.json
    28-Sep-2020 11:17:25	+ rm -f astyle_report.json astyle_annotations.json
    28-Sep-2020 11:17:25	+ /scripts/bb_code_insights/astyle
    28-Sep-2020 11:17:28	Reporting on these files:  ['libplatsupport/src/chardev.h', 'libplatsupport/src/mach/zynq/serial.c']
    28-Sep-2020 11:17:28	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    28-Sep-2020 11:17:28	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    28-Sep-2020 11:17:28	+ set +x
    28-Sep-2020 11:17:29	+ '[' -f astyle_report.json ']'
    28-Sep-2020 11:17:29	+ cat astyle_report.json
    28-Sep-2020 11:17:29	+ '[' -f astyle_annotations.json ']'
    28-Sep-2020 11:17:29	+ cat astyle_annotations.json
    28-Sep-2020 11:17:29	{"data":[{"title":"Total number of files with incorrect style","value":1},{"title":"Total number of lines with incorrect style","value":7}],"createdDate":1601255848768,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 1}, {"title": "Total number of lines with incorrect style", "value": 7}]}{"annotations": [{"path": "libplatsupport/src/chardev.h", "line": 22, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "libplatsupport/src/chardev.h", "line": 33, "message": "There are 5 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "libplatsupport/src/chardev.h", "line": 59, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}]}
    28-Sep-2020 11:17:29	Finished task 'Run astyle code insights' with result: Success
    28-Sep-2020 11:17:29	Running post build plugin 'NCover Results Collector'
    28-Sep-2020 11:17:29	Running post build plugin 'Artifact Copier'
    28-Sep-2020 11:17:29	Running post build plugin 'npm Cache Cleanup'
    28-Sep-2020 11:17:29	Running post build plugin 'Clover Results Collector'
    28-Sep-2020 11:17:29	Running post build plugin 'Docker Container Cleanup'
    28-Sep-2020 11:17:29	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR'
    28-Sep-2020 11:17:29	Finalising the build...
    28-Sep-2020 11:17:29	Stopping timer.
    28-Sep-2020 11:17:29	Build CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR-3 completed.
    28-Sep-2020 11:17:29	Running on server: post build plugin 'NCover Results Collector'
    28-Sep-2020 11:17:29	Running on server: post build plugin 'Build Hanging Detection Configuration'
    28-Sep-2020 11:17:29	Running on server: post build plugin 'Clover Delta Calculator'
    28-Sep-2020 11:17:29	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    28-Sep-2020 11:17:29	All post build plugins have finished
    28-Sep-2020 11:17:29	Generating build results summary...
    28-Sep-2020 11:17:29	Saving build results to disk...
    28-Sep-2020 11:17:29	Store variable context...
    28-Sep-2020 11:17:29	Indexing build results...
    28-Sep-2020 11:17:29	Finished building CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR-3.


This is the most I can report on right now, sorry!

**Comment by axel-h** [comment]
I wonder, should 
```
int uart_static_init(
    void *vaddr,	    void *vaddr,
    const ps_io_ops_t *ops,
    ps_chardevice_t *dev)
```
be changed to 
```
int uart_static_init(
    const struct dev_defn* defn,
    void *vaddr,	    void *vaddr,
    const ps_io_ops_t *ops,
    ps_chardevice_t *dev)
```
in the generic code, so one is always forced to pass a `struct dev_defn` here. All this does not really matter for the ZYNQ platform, but for other platforms like imx6 there is the mux setup necessary also for some UARTs, so this context information is needed. In the current form `uart_static_init()` is not too useful and it sets a bad example how to do things.

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 3565dcaa85d5d5fb45a65aaa69841fe91c4a77b3

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - util_libs - EXT-axel-h-axel-patch-1-43 | SUCCESSFUL |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-1-43 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-1-43 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    29-Sep-2020 08:35:02	Build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-1-43 - style #4 (CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR-4) started building on agent A local agent 1
    29-Sep-2020 08:35:02	I run on the Bamboo server!
    29-Sep-2020 08:35:02	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR
    29-Sep-2020 08:35:02	Executing build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-1-43 - style #4 (CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR-4)
    29-Sep-2020 08:35:02	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR/. (location: .)
    29-Sep-2020 08:35:02	Artifact 'code' prepared in 31.63 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR/./code.tar.gz
    29-Sep-2020 08:35:02	Running pre-build action: VCS Version Collector
    29-Sep-2020 08:35:02	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    29-Sep-2020 08:35:02	+ tar xf code.tar.gz --recursive-unlink
    29-Sep-2020 08:35:02	Finished task 'Untar code' with result: Success
    29-Sep-2020 08:35:02	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    29-Sep-2020 08:35:02	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR
    29-Sep-2020 08:35:03	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    29-Sep-2020 08:35:03	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    29-Sep-2020 08:35:03	+ cd util_libs
    29-Sep-2020 08:35:03	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR/seL4_tools/misc/style.sh
    29-Sep-2020 08:35:03	++ git merge-base 3565dcaa85d5d5fb45a65aaa69841fe91c4a77b3 0a642200152e84327e6921b390a0aa0a421673ef
    29-Sep-2020 08:35:03	+ git diff --name-only 3565dcaa85d5d5fb45a65aaa69841fe91c4a77b3 0a642200152e84327e6921b390a0aa0a421673ef
    29-Sep-2020 08:35:03	Formatted  libplatsupport/src/chardev.h
    29-Sep-2020 08:35:03	Unchanged  libplatsupport/src/mach/zynq/serial.c
    29-Sep-2020 08:35:03	+ git diff --exit-code
    29-Sep-2020 08:35:03	diff --git a/libplatsupport/src/chardev.h b/libplatsupport/src/chardev.h
    29-Sep-2020 08:35:03	index 5fb545d..9ba425d 100644
    29-Sep-2020 08:35:03	--- a/libplatsupport/src/chardev.h
    29-Sep-2020 08:35:03	+++ b/libplatsupport/src/chardev.h
    29-Sep-2020 08:35:03	@@ -30,7 +30,7 @@ static inline void *chardev_map(
    29-Sep-2020 08:35:03	     const ps_io_ops_t *ops)
    29-Sep-2020 08:35:03	 {
    29-Sep-2020 08:35:03	     return ps_io_map(
    29-Sep-2020 08:35:03	-               (ps_io_mapper_t*)&ops->io_mapper, // cast removes "const" qualifier
    29-Sep-2020 08:35:03	+               (ps_io_mapper_t *)&ops->io_mapper, // cast removes "const" qualifier
    29-Sep-2020 08:35:03	                dev->paddr,
    29-Sep-2020 08:35:03	                dev->size,
    29-Sep-2020 08:35:03	                0, // map uncached
    29-Sep-2020 08:35:03	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR-4-ScriptBuildTask-2007062005170412335.sh] was 1 while expected 0
    29-Sep-2020 08:35:03	Finished task 'Check style of changed files' with result: Failed
    29-Sep-2020 08:35:03	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    29-Sep-2020 08:35:03	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR
    29-Sep-2020 08:35:03	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    29-Sep-2020 08:35:03	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    29-Sep-2020 08:35:03	+ cd util_libs
    29-Sep-2020 08:35:03	++ echo ssh://git@bitbucket.ts.data61.csiro.au:7999/sel4/util_libs.git
    29-Sep-2020 08:35:03	++ cut -d/ -f4
    29-Sep-2020 08:35:03	+ bb_proj=sel4
    29-Sep-2020 08:35:03	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4 util_libs
    29-Sep-2020 08:35:03	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    29-Sep-2020 08:35:03	+ SCRIPT_DIR=/scripts/bb_code_insights
    29-Sep-2020 08:35:03	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    29-Sep-2020 08:35:03	+ BBS_PROJECT=sel4
    29-Sep-2020 08:35:03	+ BBS_REPO=util_libs
    29-Sep-2020 08:35:03	+ REPORT_TO_RUN=astyle
    29-Sep-2020 08:35:03	++ git rev-parse HEAD
    29-Sep-2020 08:35:03	+ COMMIT_ID=3565dcaa85d5d5fb45a65aaa69841fe91c4a77b3
    29-Sep-2020 08:35:03	+ REPORT_KEY=astyle.report
    29-Sep-2020 08:35:03	+ set +x
    29-Sep-2020 08:35:03	+ report_file=astyle_report.json
    29-Sep-2020 08:35:03	+ annotations_file=astyle_annotations.json
    29-Sep-2020 08:35:03	+ rm -f astyle_report.json astyle_annotations.json
    29-Sep-2020 08:35:03	+ /scripts/bb_code_insights/astyle
    29-Sep-2020 08:35:06	Reporting on these files:  ['libplatsupport/src/chardev.h', 'libplatsupport/src/mach/zynq/serial.c']
    29-Sep-2020 08:35:06	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    29-Sep-2020 08:35:06	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    29-Sep-2020 08:35:06	+ set +x
    29-Sep-2020 08:35:06	+ '[' -f astyle_report.json ']'
    29-Sep-2020 08:35:06	+ cat astyle_report.json
    29-Sep-2020 08:35:06	+ '[' -f astyle_annotations.json ']'
    29-Sep-2020 08:35:06	+ cat astyle_annotations.json
    29-Sep-2020 08:35:06	{"data":[{"title":"Total number of files with incorrect style","value":1},{"title":"Total number of lines with incorrect style","value":1}],"createdDate":1601332506548,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 1}, {"title": "Total number of lines with incorrect style", "value": 1}]}{"annotations": [{"path": "libplatsupport/src/chardev.h", "line": 33, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}]}
    29-Sep-2020 08:35:06	Finished task 'Run astyle code insights' with result: Success
    29-Sep-2020 08:35:06	Running post build plugin 'NCover Results Collector'
    29-Sep-2020 08:35:06	Running post build plugin 'Artifact Copier'
    29-Sep-2020 08:35:06	Running post build plugin 'npm Cache Cleanup'
    29-Sep-2020 08:35:06	Running post build plugin 'Clover Results Collector'
    29-Sep-2020 08:35:06	Running post build plugin 'Docker Container Cleanup'
    29-Sep-2020 08:35:06	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR'
    29-Sep-2020 08:35:06	Finalising the build...
    29-Sep-2020 08:35:06	Stopping timer.
    29-Sep-2020 08:35:06	Build CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR-4 completed.
    29-Sep-2020 08:35:06	Running on server: post build plugin 'NCover Results Collector'
    29-Sep-2020 08:35:06	Running on server: post build plugin 'Build Hanging Detection Configuration'
    29-Sep-2020 08:35:06	Running on server: post build plugin 'Clover Delta Calculator'
    29-Sep-2020 08:35:06	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    29-Sep-2020 08:35:06	All post build plugins have finished
    29-Sep-2020 08:35:07	Generating build results summary...
    29-Sep-2020 08:35:07	Saving build results to disk...
    29-Sep-2020 08:35:07	Store variable context...
    29-Sep-2020 08:35:07	Indexing build results...
    29-Sep-2020 08:35:07	Finished building CQ-UTILLIBSSTYLE135-UTILLIBSSTYLEPR-4.


This is the most I can report on right now, sorry!

**Comment by walle-whale** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by walle-whale** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
