### PR TITLE
Fixed conflict between MUX and ethernet driver

### PR DESCRIPTION
**Pull request by fabriziobertocci**
Fixed problem described in my email to the dev mailing list:

In short, the problem is that platsupport takes ownership of the entire MUX (maps the I/O) when the io_ops are initialized:
Repo: seL4/seL4_libs
File: libsel4platsupport/src/io.c
Function: sel4platsupport_new_io_ops
  ...
  mux_sys_init(io_ops, get_mux_dependencies(), &io_ops->mux_sys);
  ...

The above call end up calling the platform-specific mux_sys_init that maps only the first 4Kb of IO space from address 0x020e0000 (the base address of the IOMUX controller - note: the IOMUX controller uses 16Kb of address space for its registers, not 4Kb!!!):
Repo: seL4/util_libs
File: libplatsupport/src/plat/imx6/mux.c
Function: mux_sys_init
  ...
  MAP_IF_NULL(io_ops, IMX6_IOMUXC, _mux.iomuxc);
  return imx6_mux_init_common(mux);

The pointer "io_ops->mux_sys->priv" should point to the base address of the IOMUX of the SoC (in the virtual memory space of the calling process).

The Ethernet driver unfortunately attempts to map the IOMUX again:
Repo: seL4/util_libs
File: libethdrivers/src/plat/imx6/uboot/mx6qsabrelite.c
Function: setup_iomux_enet
  ...
  void *base = RESOURCE(&io_ops->io_mapper, IOMUXC);
  ... 
  // Modify the IOMUX registers, then release the mapped IO:
  ...
  UNRESOURCE(&io_ops->io_mapper, IOMUXC, base);
 
but using a larger size (the full 16Kb from the same base address of the IOMUX controller).

So, the ethernet controller attempt to map the IO fails because it is already mapped, and nothing works.

### CODE REVIEW

**Comment by latentPrion** [comment]
Hey, @fabriziobertocci, looking great -- just one thing I'd like to ask for: could you rebase out the merge commits? As much as possible, we've adopted a policy of trying to keep history fresh and clean on our repos -- really appreciate your time~

**Comment by latentPrion** [comment]
Sorry for the delay @fabriziobertocci and thanks for being patient:
So, what I usually do is something like `git rebase -i HEAD^10` (lazily pick the last 10 commits to be chosen from), then git should give you an interactive little screen where you can "pick", "drop" and "squash" commits from the set you chose.

What I think should work here is that you change "pick" into "drop" (or just "d") for the 2 merge commits and then let git drop them out and that should be more than okay~

**Comment by latentPrion** [comment]
@fabriziobertocci Sorry, I took a while:

Well, you can either just rebase your way through it since it's a small number of commits, or you can manually reassemble the commits on a new branch using cherry-pick:

For the rebase method, try `git rebase -i HEAD~10` to lazily select the last 10 commits to choose from, and you'll be given an interactive prompt in which you can "pick", "drop" and "squash" commits and so on; Here you want to just leave everything as it is and just save and exit, and git will then try to rebase and fail, and have you re-merge the commits. Resolve the merge conflicts and then `git add <FILE>` and `git rebase --continue` until the rebase has completed -- that should give you a new history with no merge commits.

Or you can create a new branch and then `git cherry-pick <hash>` the commits from the old branch one by one and skip the merge commit altogether.

Thanks for your patience.

**Comment by fabriziobertocci** [comment]
I have created a new pull request, cleaner this time. Let's see if that works. Once that's done I can close this one.

**Comment by pingerino** [comment]
Hi @fabriziobertocci , a new branch is fine. protip though, I learned a lot about rebasing etc using this tutorial: https://learngitbranching.js.org/

**Comment by fabriziobertocci** [comment]
Thanks Anna for the tutorial.  It seems very well done.
Regards,
Fabrizio

**Comment by lsf37** [comment]
Merged in #18

**Pull request closed without merging**
