### PR TITLE
libplatsupport,zynq: clear receive trigger interrupt also when reading chars

### PR DESCRIPTION
**Pull request by axel-h**
Clear the receive trigger interrupt when reading a character, assuming the caller is draining the FIFO anyway. This avoids unnecessary (re-)invocation of the ISR

### CODE REVIEW

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 66f2ad9ee7254b253d4429be0243e20617c833ee

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - util_libs - EXT-axel-h-axel-patch-4-44 | SUCCESSFUL |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-4-44 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-4-44 | Style check on changed files | 1 of 3 jobs failed |

**Job: gitlint**
Build logs

    23-Sep-2020 13:56:18	Build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-4-44 - gitlint #1 (CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR-1) started building on agent A local agent 2
    23-Sep-2020 13:56:18	I run on the Bamboo server!
    23-Sep-2020 13:56:18	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR
    23-Sep-2020 13:56:18	Executing build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-4-44 - gitlint #1 (CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR-1)
    23-Sep-2020 13:56:18	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR/. (location: .)
    23-Sep-2020 13:56:18	Artifact 'code' prepared in 32.60 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR/./code.tar.gz
    23-Sep-2020 13:56:18	Running pre-build action: VCS Version Collector
    23-Sep-2020 13:56:18	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Sep-2020 13:56:18	+ tar xf code.tar.gz --recursive-unlink
    23-Sep-2020 13:56:18	Finished task 'Untar code' with result: Success
    23-Sep-2020 13:56:18	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Sep-2020 13:56:18	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR
    23-Sep-2020 13:56:18	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    23-Sep-2020 13:56:18	Starting task 'Lint commit messages' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Sep-2020 13:56:18	+ cd util_libs
    23-Sep-2020 13:56:18	+ '[' -f .gitlint ']'
    23-Sep-2020 13:56:18	+ CONFIG=/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR/seL4_tools/misc/.gitlint
    23-Sep-2020 13:56:18	+ gitlint --commits a6a56d64142c91d7be8c4c4f96e973b72ef5b5f2..66f2ad9ee7254b253d4429be0243e20617c833ee --config /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR/seL4_tools/misc/.gitlint
    23-Sep-2020 13:56:22	1: T1 Title exceeds max length (52>50): "libplatsupport,zynq: clear receive trigger interrupt"
    23-Sep-2020 13:56:22	3: B1 Line exceeds max length (111>72): "Clear the receive trigger interrupt when reading a character, assuming the caller is draining the FIFO anyway. "
    23-Sep-2020 13:56:22	3: B2 Line has trailing whitespace: "Clear the receive trigger interrupt when reading a character, assuming the caller is draining the FIFO anyway. "
    23-Sep-2020 13:56:22	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR-1-ScriptBuildTask-8253818808999634401.sh] was 3 while expected 0
    23-Sep-2020 13:56:22	Finished task 'Lint commit messages' with result: Failed
    23-Sep-2020 13:56:22	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Sep-2020 13:56:22	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR
    23-Sep-2020 13:56:22	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    23-Sep-2020 13:56:22	Running post build plugin 'NCover Results Collector'
    23-Sep-2020 13:56:22	Running post build plugin 'Artifact Copier'
    23-Sep-2020 13:56:22	Running post build plugin 'npm Cache Cleanup'
    23-Sep-2020 13:56:22	Running post build plugin 'Clover Results Collector'
    23-Sep-2020 13:56:22	Running post build plugin 'Docker Container Cleanup'
    23-Sep-2020 13:56:23	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR'
    23-Sep-2020 13:56:23	Finalising the build...
    23-Sep-2020 13:56:23	Stopping timer.
    23-Sep-2020 13:56:23	Build CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR-1 completed.
    23-Sep-2020 13:56:23	Running on server: post build plugin 'NCover Results Collector'
    23-Sep-2020 13:56:23	Running on server: post build plugin 'Build Hanging Detection Configuration'
    23-Sep-2020 13:56:23	Running on server: post build plugin 'Clover Delta Calculator'
    23-Sep-2020 13:56:23	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    23-Sep-2020 13:56:23	All post build plugins have finished
    23-Sep-2020 13:56:23	Generating build results summary...
    23-Sep-2020 13:56:23	Saving build results to disk...
    23-Sep-2020 13:56:23	Store variable context...
    23-Sep-2020 13:56:23	Indexing build results...
    23-Sep-2020 13:56:23	Finished building CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR-1.


This is the most I can report on right now, sorry!

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 384b85b2cdade12a776304fd81ce5eb3192dc332

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - util_libs - EXT-axel-h-axel-patch-4-44 | SUCCESSFUL |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-4-44 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-4-44 | Style check on changed files | 1 of 3 jobs failed |

**Job: gitlint**
Build logs

    23-Sep-2020 14:25:47	Build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-4-44 - gitlint #2 (CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR-2) started building on agent A local agent 1
    23-Sep-2020 14:25:47	I run on the Bamboo server!
    23-Sep-2020 14:25:47	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR
    23-Sep-2020 14:25:47	Executing build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-4-44 - gitlint #2 (CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR-2)
    23-Sep-2020 14:25:47	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR/. (location: .)
    23-Sep-2020 14:25:47	Artifact 'code' prepared in 68.64 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR/./code.tar.gz
    23-Sep-2020 14:25:47	Running pre-build action: VCS Version Collector
    23-Sep-2020 14:25:47	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Sep-2020 14:25:47	+ tar xf code.tar.gz --recursive-unlink
    23-Sep-2020 14:25:47	Finished task 'Untar code' with result: Success
    23-Sep-2020 14:25:47	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Sep-2020 14:25:47	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR
    23-Sep-2020 14:25:47	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    23-Sep-2020 14:25:47	Starting task 'Lint commit messages' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Sep-2020 14:25:47	+ cd util_libs
    23-Sep-2020 14:25:47	+ '[' -f .gitlint ']'
    23-Sep-2020 14:25:47	+ CONFIG=/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR/seL4_tools/misc/.gitlint
    23-Sep-2020 14:25:47	+ gitlint --commits a6a56d64142c91d7be8c4c4f96e973b72ef5b5f2..384b85b2cdade12a776304fd81ce5eb3192dc332 --config /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR/seL4_tools/misc/.gitlint
    23-Sep-2020 14:25:51	4: B2 Line has trailing whitespace: "the caller is draining the FIFO anyway. "
    23-Sep-2020 14:25:51	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR-2-ScriptBuildTask-7726094596557404146.sh] was 1 while expected 0
    23-Sep-2020 14:25:51	Finished task 'Lint commit messages' with result: Failed
    23-Sep-2020 14:25:51	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    23-Sep-2020 14:25:51	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR
    23-Sep-2020 14:25:51	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    23-Sep-2020 14:25:51	Running post build plugin 'NCover Results Collector'
    23-Sep-2020 14:25:51	Running post build plugin 'Artifact Copier'
    23-Sep-2020 14:25:51	Running post build plugin 'npm Cache Cleanup'
    23-Sep-2020 14:25:51	Running post build plugin 'Clover Results Collector'
    23-Sep-2020 14:25:51	Running post build plugin 'Docker Container Cleanup'
    23-Sep-2020 14:25:51	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/140083221/CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR'
    23-Sep-2020 14:25:51	Finalising the build...
    23-Sep-2020 14:25:51	Stopping timer.
    23-Sep-2020 14:25:51	Build CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR-2 completed.
    23-Sep-2020 14:25:51	Running on server: post build plugin 'NCover Results Collector'
    23-Sep-2020 14:25:51	Running on server: post build plugin 'Build Hanging Detection Configuration'
    23-Sep-2020 14:25:51	Running on server: post build plugin 'Clover Delta Calculator'
    23-Sep-2020 14:25:51	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    23-Sep-2020 14:25:51	All post build plugins have finished
    23-Sep-2020 14:25:51	Generating build results summary...
    23-Sep-2020 14:25:51	Saving build results to disk...
    23-Sep-2020 14:25:51	Store variable context...
    23-Sep-2020 14:25:51	Indexing build results...
    23-Sep-2020 14:25:51	Finished building CQ-UTILLIBSSTYLE136-UTILLIBSGITLINTPR-2.


This is the most I can report on right now, sorry!

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Review by kent-mcleod — APPROVED** [review]

**Review by lsf37 — APPROVED** [review]

**Pull request merged**
