### PR TITLE
libplatsupport: Update rockpro64 default serial

### PR DESCRIPTION
**Pull request by kent-mcleod**
The default serial for this platform is serial2.
Also fix some register misconfiguraitons.

### CODE REVIEW

**Comment by kent-mcleod** [comment]
@ssrg-bamboo `test`

**Comment by kent-mcleod** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Pull request merged**
