### PR TITLE
CMake cleanup

### PR DESCRIPTION
**Pull request by axel-h**
- use variables instead of string matching
- merge `target_include_directories()` statements

### CODE REVIEW

**Review by kent-mcleod — APPROVED** [review]

**Comment by axel-h** [comment]
Sorry, rebased this to the wrong base accidentally. Can we merge this, that would help avoiding conflicts with some other changes.

**Comment by axel-h** [comment]
seem the build errors for the hardware platforms are unrelated to this change, looks more like a network/mount issue?

**Comment by lsf37** [comment]
> seem the build errors for the hardware platforms are unrelated to this change, looks more like a network/mount issue?

The power supply for a lot of boards died -- a new one is now active, but the boards tx1 and zcu102_2 are still acting up. I'm hoping Peter will be able to fix them by tomorrow.

**Comment by axel-h** [comment]
Can we merge this? It has passed the CI test at least once, the failures are random CI Board issues.

**Comment by lsf37** [comment]
The boards should be much more stable again now, I've restarted the test. It'd be nice if at least the imx8mq ran successfully, because the PR mentions it.

If MULTICORE004 fails for the imx8mq on smp+hyp with clang, then that's unrelated to this PR.

**Pull request merged**
