### PR TITLE
supress-gcc-warnings: add const qualifier

### PR DESCRIPTION
**Pull request by axel-h**
Signed-off-by: Axel Heider <axelheider@gmx.de>

### CODE REVIEW

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 72bc1a9d495f661bc6d5354c005ff466d8688da3

### Summary

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - util_libs - EXT-axel-h-axel-patch-9-40 | SUCCESSFUL |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-9-40 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-9-40 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    16-Sep-2020 01:15:22	Build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-9-40 - style #1 (CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR-1) started building on agent A local agent 2
    16-Sep-2020 01:15:22	I run on the Bamboo server!
    16-Sep-2020 01:15:22	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR
    16-Sep-2020 01:15:22	Executing build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-9-40 - style #1 (CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR-1)
    16-Sep-2020 01:15:22	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR/. (location: .)
    16-Sep-2020 01:15:22	Artifact 'code' prepared in 26.56 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR/./code.tar.gz
    16-Sep-2020 01:15:22	Running pre-build action: VCS Version Collector
    16-Sep-2020 01:15:22	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    16-Sep-2020 01:15:22	+ tar xf code.tar.gz --recursive-unlink
    16-Sep-2020 01:15:22	Finished task 'Untar code' with result: Success
    16-Sep-2020 01:15:22	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    16-Sep-2020 01:15:22	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR
    16-Sep-2020 01:15:22	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    16-Sep-2020 01:15:22	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    16-Sep-2020 01:15:22	+ cd util_libs
    16-Sep-2020 01:15:22	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR/seL4_tools/misc/style.sh
    16-Sep-2020 01:15:22	++ git merge-base 72bc1a9d495f661bc6d5354c005ff466d8688da3 28c378b51fae0c1026c4c5a4b85610229a6922aa
    16-Sep-2020 01:15:22	+ git diff --name-only 72bc1a9d495f661bc6d5354c005ff466d8688da3 2c4603aa68963e7285ba98d4133b31097d7878a6
    16-Sep-2020 01:15:22	Formatted  libplatsupport/src/mach/zynq/mux.c
    16-Sep-2020 01:15:22	+ git diff --exit-code
    16-Sep-2020 01:15:22	diff --git a/libplatsupport/src/mach/zynq/mux.c b/libplatsupport/src/mach/zynq/mux.c
    16-Sep-2020 01:15:22	index 08bb196..c33f83a 100644
    16-Sep-2020 01:15:22	--- a/libplatsupport/src/mach/zynq/mux.c
    16-Sep-2020 01:15:22	+++ b/libplatsupport/src/mach/zynq/mux.c
    16-Sep-2020 01:15:22	@@ -19,39 +19,35 @@
    16-Sep-2020 01:15:22	 struct slcr;
    16-Sep-2020 01:15:22	 
    16-Sep-2020 01:15:22	 static struct zynq_mux {
    16-Sep-2020 01:15:22	-    struct slcr* slcr;
    16-Sep-2020 01:15:22	+    struct slcr *slcr;
    16-Sep-2020 01:15:22	 } _mux;
    16-Sep-2020 01:15:22	 
    16-Sep-2020 01:15:22	-static inline void set_mux_priv(mux_sys_t* mux, struct zynq_mux* zynq_mux)
    16-Sep-2020 01:15:22	+static inline void set_mux_priv(mux_sys_t *mux, struct zynq_mux *zynq_mux)
    16-Sep-2020 01:15:22	 {
    16-Sep-2020 01:15:22	     assert(mux != NULL);
    16-Sep-2020 01:15:22	     assert(zynq_mux != NULL);
    16-Sep-2020 01:15:22	     mux->priv = zynq_mux;
    16-Sep-2020 01:15:22	 }
    16-Sep-2020 01:15:22	 
    16-Sep-2020 01:15:22	-static int
    16-Sep-2020 01:15:22	-zynq_mux_feature_enable(const mux_sys_t* mux, mux_feature_t mux_feature,
    16-Sep-2020 01:15:22	-                        UNUSED enum mux_gpio_dir mgd)
    16-Sep-2020 01:15:22	+static int zynq_mux_feature_enable(const mux_sys_t *mux, mux_feature_t mux_feature,
    16-Sep-2020 01:15:22	+                                   UNUSED enum mux_gpio_dir mgd)
    16-Sep-2020 01:15:22	 {
    16-Sep-2020 01:15:22	     return 0;
    16-Sep-2020 01:15:22	 }
    16-Sep-2020 01:15:22	 
    16-Sep-2020 01:15:22	-static int
    16-Sep-2020 01:15:22	-zynq_mux_init_common(mux_sys_t* mux)
    16-Sep-2020 01:15:22	+static int zynq_mux_init_common(mux_sys_t *mux)
    16-Sep-2020 01:15:22	 {
    16-Sep-2020 01:15:22	     set_mux_priv(mux, &_mux);
    16-Sep-2020 01:15:22	     mux->feature_enable = &zynq_mux_feature_enable;
    16-Sep-2020 01:15:22	     return 0;
    16-Sep-2020 01:15:22	 }
    16-Sep-2020 01:15:22	 
    16-Sep-2020 01:15:22	-int
    16-Sep-2020 01:15:22	-zynq_mux_init(mux_sys_t* mux)
    16-Sep-2020 01:15:22	+int zynq_mux_init(mux_sys_t *mux)
    16-Sep-2020 01:15:22	 {
    16-Sep-2020 01:15:22	     return zynq_mux_init_common(mux);
    16-Sep-2020 01:15:22	 }
    16-Sep-2020 01:15:22	 
    16-Sep-2020 01:15:22	-int
    16-Sep-2020 01:15:22	-mux_sys_init(ps_io_ops_t* io_ops, UNUSED void *dependencies, mux_sys_t* mux)
    16-Sep-2020 01:15:22	+int mux_sys_init(ps_io_ops_t *io_ops, UNUSED void *dependencies, mux_sys_t *mux)
    16-Sep-2020 01:15:22	 {
    16-Sep-2020 01:15:22	     return zynq_mux_init_common(mux);
    16-Sep-2020 01:15:22	 }
    16-Sep-2020 01:15:22	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR-1-ScriptBuildTask-603503624994875136.sh] was 1 while expected 0
    16-Sep-2020 01:15:22	Finished task 'Check style of changed files' with result: Failed
    16-Sep-2020 01:15:22	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    16-Sep-2020 01:15:22	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR
    16-Sep-2020 01:15:23	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    16-Sep-2020 01:15:23	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    16-Sep-2020 01:15:23	+ cd util_libs
    16-Sep-2020 01:15:23	++ echo ssh://git@bitbucket.ts.data61.csiro.au:7999/sel4/util_libs.git
    16-Sep-2020 01:15:23	++ cut -d/ -f4
    16-Sep-2020 01:15:23	+ bb_proj=sel4
    16-Sep-2020 01:15:23	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4 util_libs
    16-Sep-2020 01:15:23	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    16-Sep-2020 01:15:23	+ SCRIPT_DIR=/scripts/bb_code_insights
    16-Sep-2020 01:15:23	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    16-Sep-2020 01:15:23	+ BBS_PROJECT=sel4
    16-Sep-2020 01:15:23	+ BBS_REPO=util_libs
    16-Sep-2020 01:15:23	+ REPORT_TO_RUN=astyle
    16-Sep-2020 01:15:23	++ git rev-parse HEAD
    16-Sep-2020 01:15:23	+ COMMIT_ID=72bc1a9d495f661bc6d5354c005ff466d8688da3
    16-Sep-2020 01:15:23	+ REPORT_KEY=astyle.report
    16-Sep-2020 01:15:23	+ set +x
    16-Sep-2020 01:15:23	+ report_file=astyle_report.json
    16-Sep-2020 01:15:23	+ annotations_file=astyle_annotations.json
    16-Sep-2020 01:15:23	+ rm -f astyle_report.json astyle_annotations.json
    16-Sep-2020 01:15:23	+ /scripts/bb_code_insights/astyle
    16-Sep-2020 01:15:25	Reporting on these files:  ['libplatsupport/plat_include/rockpro64/platsupport/plat/timer.h', 'libplatsupport/src/mach/zynq/mux.c', 'libplatsupport/src/plat/rockpro64/timer.c']
    16-Sep-2020 01:15:25	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    16-Sep-2020 01:15:25	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    16-Sep-2020 01:15:25	+ set +x
    16-Sep-2020 01:15:26	+ '[' -f astyle_report.json ']'
    16-Sep-2020 01:15:26	+ cat astyle_report.json
    16-Sep-2020 01:15:26	+ '[' -f astyle_annotations.json ']'
    16-Sep-2020 01:15:26	+ cat astyle_annotations.json
    16-Sep-2020 01:15:26	{"data":[{"title":"Total number of files with incorrect style","value":1},{"title":"Total number of lines with incorrect style","value":11}],"createdDate":1600182925990,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 1}, {"title": "Total number of lines with incorrect style", "value": 11}]}{"annotations": [{"path": "libplatsupport/src/mach/zynq/mux.c", "line": 22, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "libplatsupport/src/mach/zynq/mux.c", "line": 25, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "libplatsupport/src/mach/zynq/mux.c", "line": 32, "message": "There are 3 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "libplatsupport/src/mach/zynq/mux.c", "line": 39, "message": "There are 2 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "libplatsupport/src/mach/zynq/mux.c", "line": 47, "message": "There are 2 line(s) of incorrect style here.", "severity": "HIGH"}, {"path": "libplatsupport/src/mach/zynq/mux.c", "line": 53, "message": "There are 2 line(s) of incorrect style here.", "severity": "HIGH"}]}
    16-Sep-2020 01:15:26	Finished task 'Run astyle code insights' with result: Success
    16-Sep-2020 01:15:26	Running post build plugin 'NCover Results Collector'
    16-Sep-2020 01:15:26	Running post build plugin 'Artifact Copier'
    16-Sep-2020 01:15:26	Running post build plugin 'npm Cache Cleanup'
    16-Sep-2020 01:15:26	Running post build plugin 'Clover Results Collector'
    16-Sep-2020 01:15:26	Running post build plugin 'Docker Container Cleanup'
    16-Sep-2020 01:15:26	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR'
    16-Sep-2020 01:15:26	Finalising the build...
    16-Sep-2020 01:15:26	Stopping timer.
    16-Sep-2020 01:15:26	Build CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR-1 completed.
    16-Sep-2020 01:15:26	Running on server: post build plugin 'NCover Results Collector'
    16-Sep-2020 01:15:26	Running on server: post build plugin 'Build Hanging Detection Configuration'
    16-Sep-2020 01:15:26	Running on server: post build plugin 'Clover Delta Calculator'
    16-Sep-2020 01:15:26	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    16-Sep-2020 01:15:26	All post build plugins have finished
    16-Sep-2020 01:15:26	Generating build results summary...
    16-Sep-2020 01:15:26	Saving build results to disk...
    16-Sep-2020 01:15:26	Store variable context...
    16-Sep-2020 01:15:26	Indexing build results...
    16-Sep-2020 01:15:26	Finished building CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR-1.


This is the most I can report on right now, sorry!

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
## Test results for commit 36d9c11bfc0c9ff462104e912e2da6bb75bf1e57

### Summary

#### NOTE: some test results have been updated!

| Test name | Result |
| --- | --- |
| Code Quality - Check licenses - util_libs - EXT-axel-h-axel-patch-9-40 | SUCCESSFUL |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-9-40 | FAILED |

### Detailed failure logs

| Project | Stage | Result summary |
| --- | --- | --- |
| Code Quality - Style - util_libs - EXT-axel-h-axel-patch-9-40 | Style check on changed files | 1 of 3 jobs failed |

**Job: style**
Build logs

    16-Sep-2020 01:28:02	Build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-9-40 - style #2 (CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR-2) started building on agent A local agent 2
    16-Sep-2020 01:28:02	I run on the Bamboo server!
    16-Sep-2020 01:28:02	Build working directory is /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR
    16-Sep-2020 01:28:02	Executing build Code Quality - Style - util_libs - EXT-axel-h-axel-patch-9-40 - style #2 (CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR-2)
    16-Sep-2020 01:28:02	Preparing artifact 'code' for use at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR/. (location: .)
    16-Sep-2020 01:28:02	Artifact 'code' prepared in 31.82 ms at /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR/./code.tar.gz
    16-Sep-2020 01:28:02	Running pre-build action: VCS Version Collector
    16-Sep-2020 01:28:02	Starting task 'Untar code' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    16-Sep-2020 01:28:02	+ tar xf code.tar.gz --recursive-unlink
    16-Sep-2020 01:28:02	Finished task 'Untar code' with result: Success
    16-Sep-2020 01:28:02	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    16-Sep-2020 01:28:02	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR
    16-Sep-2020 01:28:02	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    16-Sep-2020 01:28:02	Starting task 'Check style of changed files' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    16-Sep-2020 01:28:02	+ cd util_libs
    16-Sep-2020 01:28:02	+ xargs -d '\n' /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR/seL4_tools/misc/style.sh
    16-Sep-2020 01:28:02	++ git merge-base 36d9c11bfc0c9ff462104e912e2da6bb75bf1e57 28c378b51fae0c1026c4c5a4b85610229a6922aa
    16-Sep-2020 01:28:02	+ git diff --name-only 36d9c11bfc0c9ff462104e912e2da6bb75bf1e57 2c4603aa68963e7285ba98d4133b31097d7878a6
    16-Sep-2020 01:28:02	Formatted  libplatsupport/src/mach/zynq/mux.c
    16-Sep-2020 01:28:02	+ git diff --exit-code
    16-Sep-2020 01:28:03	diff --git a/libplatsupport/src/mach/zynq/mux.c b/libplatsupport/src/mach/zynq/mux.c
    16-Sep-2020 01:28:03	index a74140c..2cc4a12 100644
    16-Sep-2020 01:28:03	--- a/libplatsupport/src/mach/zynq/mux.c
    16-Sep-2020 01:28:03	+++ b/libplatsupport/src/mach/zynq/mux.c
    16-Sep-2020 01:28:03	@@ -32,7 +32,7 @@ static inline void set_mux_priv(
    16-Sep-2020 01:28:03	 }
    16-Sep-2020 01:28:03	 
    16-Sep-2020 01:28:03	 static int zynq_mux_feature_enable(
    16-Sep-2020 01:28:03	-    const mux_sys_t* mux,
    16-Sep-2020 01:28:03	+    const mux_sys_t *mux,
    16-Sep-2020 01:28:03	     mux_feature_t mux_feature,
    16-Sep-2020 01:28:03	     UNUSED enum mux_gpio_dir mgd)
    16-Sep-2020 01:28:03	 {
    16-Sep-2020 01:28:03	Failing task since return code of [/var/atlassian/application-data/bamboo/temp/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR-2-ScriptBuildTask-3396727616350738767.sh] was 1 while expected 0
    16-Sep-2020 01:28:03	Finished task 'Check style of changed files' with result: Failed
    16-Sep-2020 01:28:03	Starting task 'Set permissions so Bamboo can cleanup' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    16-Sep-2020 01:28:03	+ chmod -R o+rwx /var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR
    16-Sep-2020 01:28:03	Finished task 'Set permissions so Bamboo can cleanup' with result: Success
    16-Sep-2020 01:28:03	Starting task 'Run astyle code insights' of type 'com.atlassian.bamboo.plugins.scripttask:task.builder.script'
    16-Sep-2020 01:28:03	+ cd util_libs
    16-Sep-2020 01:28:03	++ echo ssh://git@bitbucket.ts.data61.csiro.au:7999/sel4/util_libs.git
    16-Sep-2020 01:28:03	++ cut -d/ -f4
    16-Sep-2020 01:28:03	+ bb_proj=sel4
    16-Sep-2020 01:28:03	+ /scripts/bb_code_insights/create_code_insights.sh astyle sel4 util_libs
    16-Sep-2020 01:28:03	++ dirname /scripts/bb_code_insights/create_code_insights.sh
    16-Sep-2020 01:28:03	+ SCRIPT_DIR=/scripts/bb_code_insights
    16-Sep-2020 01:28:03	+ BBS_URL=https://bitbucket.ts.data61.csiro.au
    16-Sep-2020 01:28:03	+ BBS_PROJECT=sel4
    16-Sep-2020 01:28:03	+ BBS_REPO=util_libs
    16-Sep-2020 01:28:03	+ REPORT_TO_RUN=astyle
    16-Sep-2020 01:28:03	++ git rev-parse HEAD
    16-Sep-2020 01:28:03	+ COMMIT_ID=36d9c11bfc0c9ff462104e912e2da6bb75bf1e57
    16-Sep-2020 01:28:03	+ REPORT_KEY=astyle.report
    16-Sep-2020 01:28:03	+ set +x
    16-Sep-2020 01:28:03	+ report_file=astyle_report.json
    16-Sep-2020 01:28:03	+ annotations_file=astyle_annotations.json
    16-Sep-2020 01:28:03	+ rm -f astyle_report.json astyle_annotations.json
    16-Sep-2020 01:28:03	+ /scripts/bb_code_insights/astyle
    16-Sep-2020 01:28:05	Reporting on these files:  ['libplatsupport/plat_include/rockpro64/platsupport/plat/timer.h', 'libplatsupport/src/mach/zynq/mux.c', 'libplatsupport/src/plat/rockpro64/timer.c']
    16-Sep-2020 01:28:05	+ echo 'Reporting the results to BitBucket, but doing so *secretly*, so people don'\''t see the access token'
    16-Sep-2020 01:28:05	Reporting the results to BitBucket, but doing so *secretly*, so people don't see the access token
    16-Sep-2020 01:28:05	+ set +x
    16-Sep-2020 01:28:06	+ '[' -f astyle_report.json ']'
    16-Sep-2020 01:28:06	+ cat astyle_report.json
    16-Sep-2020 01:28:06	+ '[' -f astyle_annotations.json ']'
    16-Sep-2020 01:28:06	+ cat astyle_annotations.json
    16-Sep-2020 01:28:06	{"data":[{"title":"Total number of files with incorrect style","value":1},{"title":"Total number of lines with incorrect style","value":1}],"createdDate":1600183686083,"key":"astyle.report","title":"Code style"}{"title": "Code style", "data": [{"title": "Total number of files with incorrect style", "value": 1}, {"title": "Total number of lines with incorrect style", "value": 1}]}{"annotations": [{"path": "libplatsupport/src/mach/zynq/mux.c", "line": 35, "message": "There are 1 line(s) of incorrect style here.", "severity": "HIGH"}]}
    16-Sep-2020 01:28:06	Finished task 'Run astyle code insights' with result: Success
    16-Sep-2020 01:28:06	Running post build plugin 'NCover Results Collector'
    16-Sep-2020 01:28:06	Running post build plugin 'Artifact Copier'
    16-Sep-2020 01:28:06	Running post build plugin 'npm Cache Cleanup'
    16-Sep-2020 01:28:06	Running post build plugin 'Clover Results Collector'
    16-Sep-2020 01:28:06	Running post build plugin 'Docker Container Cleanup'
    16-Sep-2020 01:28:06	Successfully removed working directory at '/var/atlassian/application-data/bamboo/xml-data/build-dir/151224373/CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR'
    16-Sep-2020 01:28:06	Finalising the build...
    16-Sep-2020 01:28:06	Stopping timer.
    16-Sep-2020 01:28:06	Build CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR-2 completed.
    16-Sep-2020 01:28:06	Running on server: post build plugin 'NCover Results Collector'
    16-Sep-2020 01:28:06	Running on server: post build plugin 'Build Hanging Detection Configuration'
    16-Sep-2020 01:28:06	Running on server: post build plugin 'Clover Delta Calculator'
    16-Sep-2020 01:28:06	Running on server: post build plugin 'Maven Dependencies Postprocessor'
    16-Sep-2020 01:28:06	All post build plugins have finished
    16-Sep-2020 01:28:06	Generating build results summary...
    16-Sep-2020 01:28:06	Saving build results to disk...
    16-Sep-2020 01:28:06	Store variable context...
    16-Sep-2020 01:28:06	Indexing build results...
    16-Sep-2020 01:28:06	Finished building CQ-UTILLIBSSTYLE132-UTILLIBSSTYLEPR-2.


This is the most I can report on right now, sorry!

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by walle-whale** [comment]
Hey @axel-h could you rebase on master, then I can merge. Cheers!

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by axel-h** [comment]
@walle-whale I've rebased it

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Comment by walle-whale** [comment]
Thanks :)

**Pull request merged**
