### PR TITLE
Update mach timer.h to use axi instead of amba

### PR DESCRIPTION
**Pull request by chrisguikema**
Test with: https://github.com/seL4/seL4/pull/1102

### CODE REVIEW

**Comment by axel-h** [comment]
> Updates to the kernel device tree forces this change.

Can you extend this comment comment with some version details, so it gets more transparent where this happened. Guessing from your branch name it seems peta linux 2021.1 needs this?

**Comment by chrisguikema** [comment]
> > Updates to the kernel device tree forces this change.
> 
> Can you extend this comment comment with some version details, so it gets more transparent where this happened. Guessing from your branch name it seems peta linux 2021.1 needs this?

Done.

I updated the kernel PR to add the option to select a specific petalinux version

**Comment by axel-h** [comment]
> I updated the kernel PR to add the option to select a specific petalinux version

This seem to allows some transition then. But I wonder it such a config option is really needed practically. We could just move on and support a newer version (where the commit comment says, what version this is). If the expect everybody to move to this version anyway, there is not much gain keeping support for older version. Or you have to keep your own fork then for legacy support.
I wonder if a long term solution must be factoring this out of the C code into some config file, so we can have profiles.

**Comment by chrisguikema** [comment]
> But I wonder it such a config option is really needed practically. 

I agree with you. But a theme of the PRs I've made is not breaking existing features/support. While updating to 2021.1 now would _probably_ be okay, once zcu102 configurations are released to camkes-vm-apps, then future updates to the kernel would be breaking. This feels like a good compromise, where we can just release a new version without introducing any breaking changes.

**Comment by chrisguikema** [comment]
Not needed based on kernel PR feedback.

**Pull request closed without merging**
