### PR TITLE
Fix generic timer and add PER_CPU

### PR DESCRIPTION
**Pull request by pingerino**

### CODE REVIEW

**Comment by nomadeel** [comment]
Thanks for fixing this, I probably should've tested this more thoroughly. I'll pull in these commits now.

**Comment by nomadeel** [comment]
I rebased your branch against master.

**Comment by nomadeel** [comment]
Added some fixes to also fixed up the style. The PR looks good to be pulled in now.

**Comment by pingerino** [comment]
thanks!

**Pull request merged**
