### PR TITLE
libfdt: Add 32/64-bit fdt_appendprop_uint()

### PR DESCRIPTION
**Pull request by hlyytine**
Adds a convenience function that reduces the number of 'if' statements in the code, since #cells required is given as a parameter.

### CODE REVIEW

**Comment by hlyytine** [comment]
Seems that style check fails, even though `libfdt` shouldn't be checked against seL4 style rules. I just can't remember what file I am supposed to add to bypass the check for this?

**Comment by hlyytine** [comment]
Note that seL4/sel4_projects_libs#108 is also required.

**Comment by hlyytine** [comment]
> It has `libfdt` in there, but his does not work. Using `libfdt/*` seems to be the proper expression to use.

That did the trick, thanks.

**Comment by axel-h** [comment]
> > It has `libfdt` in there, but his does not work. Using `libfdt/*` seems to be the proper expression to use.
> 
> That did the trick, thanks.

Could you make the stylefilter change a separate commit?

**Comment by axel-h** [comment]
> Note that [seL4/seL4_projects_libs#108](https://github.com/seL4/seL4_projects_libs/pull/108) is also required (just found out you had accepted [seL4/camkes-vm#107](https://github.com/seL4/camkes-vm/pull/107), but the other repo does not have reviews)

For this PR here it is not needed, it just depends on it. Or did I ger something wrong?

**Comment by hlyytine** [comment]
> For this PR here it is not needed, it just depends on it. Or did I ger something wrong?

Never mind, it was just too early morning for me.

**Review by kent-mcleod — APPROVED** [review]

**Pull request merged**
