### PR TITLE
imx_ltimer: use correct size for free

### PR DESCRIPTION
**Pull request by axel-h**
addresses https://github.com/seL4/util_libs/issues/53

### CODE REVIEW

**Comment by axel-h** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by ssrg-bamboo** [comment]
All the tests we ran have passed! Nice job!

**Review by kent-mcleod — APPROVED** [review]

**Comment by axel-h** [comment]
Could you merge this, please?

**Comment by xurtis** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by xurtis** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by axel-h** [comment]
Seems bamboo is stuck?

**Comment by xurtis** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by xurtis** [comment]
@ssrg-bamboo `test`

**Comment by ssrg-bamboo** [comment]
Hello, I'm a bot! I'll bring this PR into Trustworthy Systems and run some tests

**Comment by xurtis** [comment]
This has been merged internally, the changes should hopefully be shown externally soon

**Pull request merged**
