### PR TITLE
RPi3/4 libplatsupport fixes and updates

### PR DESCRIPTION
**Pull request by JoonasOnatsu**
This PR adds various fixes and updates for RPi3/4 platforms:

- Fixed serial port drivers to use receive interrupts,
  enabling the use of virtio_console.
- General code refactoring and style updates.
- Patch for using only the system timer for ltimer component,
  leaving SP804 timer to be used for other purposes.
- Moving identical hardware drivers to generic 'bcm' machine directory.
  Serial drivers, mailbox etc.
- Some trivial fixes for GPIO driver.

Test with: seL4/seL4#894, seL4/global-components#38

### CODE REVIEW

**Comment by wom-bat** [comment]
This looks like a worthwhile refactoring.  I think it should be reviewed by someone else as well (? @kent-mcleod ?) . merged, and then another refactoring happen to pull the PL011 code out into a more generic place than the BCM area.

**Comment by JoonasOnatsu** [comment]
Thanks. I updated some files just now due to style checks failing.
And I agree that generic driver code like PL011 should probably
be moved somewhere else.

**Comment by kent-mcleod** [comment]
> This looks like a worthwhile refactoring. I think it should be reviewed by someone else as well (? @kent-mcleod ?) . merged, and then another refactoring happen to pull the PL011 code out into a more generic place than the BCM area.

I've looked over it, but not too closely, as I don't have much familiarity with either BCM platforms.

**Review by kent-mcleod — APPROVED** [review]

**Comment by lsf37** [comment]
It looks like this PR has broken the sel4test build for RPI3: https://github.com/seL4/seL4/actions/runs/3315228342/jobs/5475547078#step:3:41911

@JoonasOnatsu @kent-mcleod could you have a look please?

```
  /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c: In function ‘pl011_uart_init’:
  /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c:262:23: error: ‘UART2_OFFSET’ undeclared (first use in this function); did you mean ‘UART1_OFFSET’?
    262 |         addr_offset = UART2_OFFSET;
        |                       ^~~~~~~~~~~~
        |                       UART1_OFFSET
  /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c:262:23: note: each undeclared identifier is reported only once for each function it appears in
  /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c:265:23: error: ‘UART3_OFFSET’ undeclared (first use in this function); did you mean ‘UART1_OFFSET’?
    265 |         addr_offset = UART3_OFFSET;
        |                       ^~~~~~~~~~~~
        |                       UART1_OFFSET
  /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c:268:23: error: ‘UART4_OFFSET’ undeclared (first use in this function); did you mean ‘UART1_OFFSET’?
    268 |         addr_offset = UART4_OFFSET;
        |                       ^~~~~~~~~~~~
        |                       UART1_OFFSET
  /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c:271:23: error: ‘UART5_OFFSET’ undeclared (first use in this function); did you mean ‘UART1_OFFSET’?
    271 |         addr_offset = UART5_OFFSET;
        |                       ^~~~~~~~~~~~
        |                       UART1_OFFSET
  [83/309] Building C object apps/sel4test-driver/util_libs/libplatsupport/CMakeFiles/platsupport.dir/src/mach/bcm/serial.c.obj
  [84/309] Building C object kernel/CMakeFiles/kernel.elf.dir/kernel_all.c.obj
  ninja: build stopped: subcommand failed.
```

**Comment by JoonasOnatsu** [comment]
> It looks like this PR has broken the sel4test build for RPI3: https://github.com/seL4/seL4/actions/runs/3315228342/jobs/5475547078#step:3:41911
> 
> @JoonasOnatsu @kent-mcleod could you have a look please?
> 
> ```
>   /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c: In function ‘pl011_uart_init’:
>   /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c:262:23: error: ‘UART2_OFFSET’ undeclared (first use in this function); did you mean ‘UART1_OFFSET’?
>     262 |         addr_offset = UART2_OFFSET;
>         |                       ^~~~~~~~~~~~
>         |                       UART1_OFFSET
>   /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c:262:23: note: each undeclared identifier is reported only once for each function it appears in
>   /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c:265:23: error: ‘UART3_OFFSET’ undeclared (first use in this function); did you mean ‘UART1_OFFSET’?
>     265 |         addr_offset = UART3_OFFSET;
>         |                       ^~~~~~~~~~~~
>         |                       UART1_OFFSET
>   /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c:268:23: error: ‘UART4_OFFSET’ undeclared (first use in this function); did you mean ‘UART1_OFFSET’?
>     268 |         addr_offset = UART4_OFFSET;
>         |                       ^~~~~~~~~~~~
>         |                       UART1_OFFSET
>   /github/workspace/projects/util_libs/libplatsupport/src/mach/bcm/pl011_uart.c:271:23: error: ‘UART5_OFFSET’ undeclared (first use in this function); did you mean ‘UART1_OFFSET’?
>     271 |         addr_offset = UART5_OFFSET;
>         |                       ^~~~~~~~~~~~
>         |                       UART1_OFFSET
>   [83/309] Building C object apps/sel4test-driver/util_libs/libplatsupport/CMakeFiles/platsupport.dir/src/mach/bcm/serial.c.obj
>   [84/309] Building C object kernel/CMakeFiles/kernel.elf.dir/kernel_all.c.obj
>   ninja: build stopped: subcommand failed.
> ```

Ah dammit, it's broken here also. There is some problem with wrong header files being included for the Rpi3 build steps,
this same problem exists on my PR to the kernel also. I'm looking into it and will push fixes asap.

**Comment by JoonasOnatsu** [comment]
@kent-mcleod @lsf37 This problem is now fixed in https://github.com/seL4/util_libs/pull/140
Please check the PR so that the build failures can be fixed.

Sorry for the inconvenience, should remember to always do all the test builds before making a PR.

**Comment by kent-mcleod** [comment]
> @kent-mcleod @lsf37 This problem is now fixed in #140 Please check the PR so that the build failures can be fixed.
> 
> Sorry for the inconvenience, should remember to always do all the test builds before making a PR.

I would have flicked the hw_test label on if I realized it was supported for this repository.

**Comment by lsf37** [comment]
> I would have flicked the hw_test label on if I realized it was supported for this repository.

I'll double-check if I completed that, but my plan was that the label should be available in all repos that are mentioned in the `sel4test` repo (and that are not a fork of something external).

**Pull request merged**
