### PR TITLE
Zcu102

### PR DESCRIPTION
**Pull request by chrisguikema**
These commits are necessary for serial server and time server support on the zynqmp.

### CODE REVIEW

**Comment by chrisguikema** [comment]
@nomadeel Now that the global-components commits have been merged in, these commits are necessary for proper zynqmp support.

On the timer side, the free-running clock will only run for ~38 seconds, which is how long the timer takes to overflow. 

The serial server will print just fine, but the interrupt handler wasn't implemented, so when getting a character, the interrupt would never actually be cleared in hardware, which would continually trigger the serial server to get a character, even if one wasn't in the fifo.

**Comment by nomadeel** [comment]
Thanks for the patches! I forgot to do this for the last PR in global-components, but could you modify some of the commit messages so that:
- the subject is less than 50 characters, and
- there's a small message in the body which describes what the commit does?

This is mainly to have our git style checker happy with these commits. 

Also, could you rebase against master or would you like me to do it? This is so that Github can detect that the patches are released into master and this PR will be closed nicely when that happens.

**Comment by chrisguikema** [comment]
Alright, I updated the commit messages per the Data61 standard and rebased against the current master. Everything should be good to go!

**Comment by nomadeel** [comment]
Sweet, I'll pull in your patches now.

**Pull request merged**
